# Generated by Django 5.2.5 on 2026-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_tabla_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Ingreso_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Ingreso_Stock', models.CharField()),
                ('Fecha_Ingreso_Stock', models.DateField()),
                ('Usuario_Salida_Stock', models.CharField()),
                ('Nombre_Ingreso_Stock', models.CharField()),
                ('Descripion_Ingreso_Stock', models.CharField()),
                ('Cantidad_Ingreso_Stock', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Salida_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Salida_Stock', models.CharField()),
                ('Fecha_Salida_Stock', models.DateField()),
                ('Usuario_Salida_Stock', models.CharField()),
                ('Nombre_Salida_Stock', models.CharField()),
                ('Descripcion_Salida_Stock', models.CharField()),
                ('Cantidad_Salida_Stock', models.CharField()),
            ],
        ),
    ]
